# Generated by Django 4.2.7 on 2024-05-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_title', models.CharField(max_length=32, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额')),
                ('create_time', models.DateField(verbose_name='入职时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstageManagement.department', verbose_name='部门名称')),
            ],
        ),
    ]
