# Generated by Django 4.2.7 on 2024-04-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_admin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
